apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mediawiki-db.fullname" . }}
  labels:
    {{- include "mediawiki-db.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mediawiki-db.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mediawiki-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediawiki-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki-db.fullname" . }}
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlUser | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki-db.fullname" . }}
                  key: mysql-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
