replicaCount: 1
image:
  repository: myuser/mediawiki-site
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: mediawiki.sample.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mediawiki-sec
      hosts:
        - mediawiki.sample.com
